### ISSUE TITLE
[BUG] Comments are not hidden

### ISSUE THREAD

**Issue by caglarongan** [Fevol/obsidian-criticmarkup#7]
Comments are not hidden even though I've selected "inline-icon" or "inline" rendering selected.

<img width="1480" alt="Screenshot 2024-02-07 at 03 25 14" src="https://github.com/Fevol/obsidian-criticmarkup/assets/112904909/ec20a4db-96ca-4096-9968-6ff5a2a5ec0b">
<img width="1480" alt="Screenshot 2024-02-07 at 03 25 10" src="https://github.com/Fevol/obsidian-criticmarkup/assets/112904909/a2c1d84c-66b3-4055-9217-f17f7ae1d681">

Very high-quality plugin, very appreciated! Thanks and congrats :)

**Comment by Fevol** [comment]
Thank you for the bug report, and the kind words!

I think that you are currently in `Source Mode`, which is why the comments are not being shown as an icon. Could you test if `Toggle Live Preview/Source mode` solves the issue?

**Comment by caglarongan** [comment]
Ah yes, it works as expected in Live Preview. Thank you.

But for Reading Mode, it's still rendered inline and not hidden.

Also, multi-line comments are rendered like this:

<img width="1374" alt="source view" src="https://github.com/Fevol/obsidian-criticmarkup/assets/112904909/628f2c1d-d697-4751-b847-25055cca0f01">
<img width="1374" alt="reading mode" src="https://github.com/Fevol/obsidian-criticmarkup/assets/112904909/a7ea29a9-cc2e-49fc-b89e-9821f081d3da">

**Comment by Fevol** [comment]
Thank you for the bug report, with the latest version [0.2.0](https://github.com/Fevol/obsidian-criticmarkup/releases/tag/0.2.0), this is now partially fixed.

If you have suggestions on how to improve comment rendering in reading mode, please feel free to open up a new issue!
